export enum ProfilePaths {
	ROOT = '/perfil',
	SUMMARY = '/perfil/resumen',
	DATA = '/perfil/datos',
	ORDERS = '/perfil/pedidos',
	PREFERENCES = '/perfil/preferencias',
	HELP = '/perfil/ayuda',
	ACCOUNTS = '/perfil/cuentas',
	PASSWORD = '/perfil/password',
	FOLLOWS = '/perfil/seguidores',
	FOLLOWING = '/perfil/siguiendo',
	MY_LISTS = '/perfil/mis-listas',
	CREATE_LIST = '/perfil/crear-lista',
	SUBSCRIPTION = '/perfil/suscripticion',
}
