/**
 * Env variables enum
 */
export enum Env {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  SELF_DOMAIN = 'SELF_DOMAIN',
  HOST_FRONT = 'HOST_FRONT',
  DATABASE_URI = 'DATABASE_URI',
  UPLOADS_STATICS_PATH_USERS = 'UPLOADS_STATICS_PATH_USERS',
  UPLOADS_STATICS_PATH_BOOKS = 'UPLOADS_STATICS_PATH_BOOKS',
  UPLOADS_STATICS_PATH_AUTHORS='UPLOADS_STATICS_PATH_AUTHORS',
  UPLOADS_STATICS_PATH_GENRES = 'UPLOADS_STATICS_PATH_GENRES',
  USER_TOKEN_KEY = 'USER_TOKEN_KEY',
  USER_TOKEN_ACTIVATE_LIFE = 'USER_TOKEN_ACTIVATE_LIFE',
  USER_TOKEN_RECOVER_LIFE = 'USER_TOKEN_RECOVER_LIFE',
  USER_TOKEN_EXPIRATION = 'USER_TOKEN_EXPIRATION',
  MAIL_HOST = 'MAIL_HOST',
  MAIL_PORT = 'MAIL_PORT',
  MAIL_TLS = 'MAIL_TLS',
  AES_KEY = 'AES_KEY',
  AES_IV = 'AES_IV',
}
