version: '3.7'
services:
  mongodb-primary:
    container_name: mongoDBNevook
    image: docker.io/bitnami/mongodb:4.4-debian-10
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=admin
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_DATABASE=nevook
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - mongodb_data_container:/bitnami/mongodb
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongoDBNevook
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on:
      - mongodb-primary
    links:
      - mongodb-primary
    networks:
      - mongo-compose-network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1080:8025
      - 1025:1025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp

volumes:
  maildir: {}
  mongodb_data_container:
    driver: local

networks:
  mongo-compose-network:
    driver: bridge
